version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: habitnow
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - VITE_API_BASE_URL=https://habitnow-api.Mukku27
    restart: unless-stopped
    # For development, you can use volumes to enable hot reloading
    # volumes:
    #   - ./src:/app/src
    #   - ./public:/app/public
    #   - ./index.html:/app/index.html
    #   - ./vite.config.ts:/app/vite.config.ts

networks:
  default:
    name: habitnow-network
    external: false 